GET http://localhost:8080/api/tasks

###

POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "Test task",
  "status": "TODO"
}

###

GET http://localhost:8080/api/tasks/1

###

DELETE http://localhost:8080/api/tasks/1